### ISSUE TITLE
`ModuleNotFoundError: No module named 'gevent.wsgi'` on any invocation of `$ loom`

### ISSUE THREAD

**Issue by ivirshup** [linnarsson-lab/loom-viewer#158]
If I try and start loom-viewer, I get a `ModueNotFoundError`. Here's an example

```bash
$ loom --help                        
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/loom", line 7, in <module>
    from loom_viewer import main
  File "/usr/local/lib/python3.6/site-packages/loom_viewer/__init__.py", line 7, in <module>
    from .loom_cli import main
  File "/usr/local/lib/python3.6/site-packages/loom_viewer/loom_cli.py", line 41, in <module>
    from .loom_server import start_server
  File "/usr/local/lib/python3.6/site-packages/loom_viewer/loom_server.py", line 28, in <module>
    import gevent.wsgi
ModuleNotFoundError: No module named 'gevent.wsgi'
```

I'm using `Python v3.6.5`, `loom-viewer v0.32.2`, `gevent v1.3.1`, and `loompy v2.0.9`. I think the `gevent.wsgi` module is just named `gevent.pywsgi` now ([relevant commit from gevent](https://github.com/gevent/gevent/commit/e469e3e01f2ec30d3a500292aac5dd38c1dc7a9f)).

**Comment by marcelm** [comment]
Same problem here. Applying the changes from PR #159 fixes it.

**Comment by JobLeonard** [comment]
Sorry, we still have to push the changes to PyPi

**Comment by holgerbrandl** [comment]
Any news? I've tried to install/run it with 
```
conda create --yes --name loomviewer python=3.6
source activate loomviewer
pip install loompy
pip install loom-viewer
loom 
```
but it still gives the error from above?
